### ISSUE TITLE
If there is no upstream repository the application fails for every functionality. 

### ISSUE THREAD

**Issue by bmaca** [ccstolley/ghub#11]
_Description:_ 
If there is no remote repository set for the repos then ```ghub``` does not work at all. 

The use case here is using the application, for my own repositories which are all ```origin```. 

_Example_
![image](https://cloud.githubusercontent.com/assets/7788699/20335608/892de938-ab89-11e6-85c2-2ef367b7c869.png)

**Comment by bmaca** [comment]
I am going to take a look at the codebase, and work on a fix.

**Comment by ccstolley** [comment]
This should be fixed in the head of master, please re-open if you discover otherwise. Thanks!

**Comment by bmaca** [comment]
@ccstolley latest code changes, have fixed this issue
